apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: volume-config
  restartPolicy: Never