apiVersion: v1
kind: Pod
metadata:
  name: configmap-env
spec:
  containers:
  - name: test-container
    image: nginx
    env:
      - name: SPECIAL_HOW_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.how
    envFrom:
      - configMapRef:
          name: env-config
  restartPolicy: Never
